### ISSUE TITLE
Server service failing on stary [BUG]

### ISSUE THREAD

**Issue by stepan-zubkov** [florgon/api#171]
**Describe the bug**
After `docker-compose up -d` i get following error:
```python
server_1           |   File "/srv/www/florgon/api/app/config.py", line 201, in <module>
server_1           |     _settings = Settings()
server_1           |   File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
server_1           |   File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
server_1           | pydantic.error_wrappers.ValidationError: 2 validation errors for Settings
server_1           | mail_from
server_1           |   value is not a valid email address (type=value_error.email)
server_1           | cache_dsn
server_1           |   invalid or missing URL scheme (type=value_error.url.scheme)
```
I can solve this error with replacing type annotations in `src/config.py` (lines 21, 42, 76)
But I get error again:
```python
server_1           |   File "/srv/www/florgon/api/app/routers/__init__.py", line 47, in include_routers
server_1           |     app.include_router(module.router, prefix=proxy_url_prefix)
server_1           |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 421, in include_router
server_1           |     self.router.include_router(
server_1           |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 694, in include_router
server_1           |     assert prefix.startswith("/"), "A path prefix must start with '/'"
server_1           | AssertionError: A path prefix must start with '/'
```
I can't solve this error
**To Reproduce**
1. Run 'docker-compose up'
2. Open docker-compose logs
3. See error

**Expected behavior**
I want to start the application without errors

**Desktop**
 - OS: KDE neon User - 5.25
 - Browser Firefox
 - Version 105.0
 - Docker 20.10.12
 - Docker-compose 1.25.0

**Comment by kirillzhosul** [comment]
As I already mentioned in private chat, this error is not being produced on local / production machines, I will research this error more to see what is wrong.

**Comment by kirillzhosul** [comment]
Tested on:
- Docker desktop: v4.12.0
- Docker engine: v20.10.17, build 100c701
- Docker compose: v2.10.2 (It is some weird that I see you are using v1 one)
- OS: Windows 10 (*)

Seems to be working fine. 
![image](https://user-images.githubusercontent.com/79853674/196151859-02aab578-6940-416c-92a2-91d1eaf66e62.png)

**Comment by kirillzhosul** [comment]
This is clean startup, I do not edit any configs (also this is fresh Windows installation without any run of `florgon/api`)

**Comment by kirillzhosul** [comment]
Can`t reproduce, for now.
Maybe one of the reasons is that you are using v1 one.

**Comment by stepan-zubkov** [comment]
Works properly on docker-compose v2.11.2
