### ISSUE TITLE
Wrong link to docs

### ISSUE THREAD

**Issue by stepan-zubkov** [florgon/api#172]
Files `docs/API_RESPONSE.md` and `docs/API_METHODS.md` have wrong link to docs url. 
Fix them according to `docs/API_ERROR_CODES.md` file

**Comment by Shikharishere** [comment]
Hey, @stepan-zubkov shikhar here, I would like to solve this issue?

**Comment by Shikharishere** [comment]
[https://florgon.space/dev/apis/auth](url)
I think this is the correct link to that.

**Comment by stepan-zubkov** [comment]
Hi @Shikharishere ! You can proceed to the solution if you want.

**Comment by Shikharishere** [comment]
Okay @stepan-zubkov . Just wanted to know that the link I provided is the correct one..

**Comment by stepan-zubkov** [comment]
Yes, It's correct

**Comment by Shikharishere** [comment]
Hey, I just created a pull request..

**Comment by kirillzhosul** [comment]
Closed by #173 by @Shikharishere
